//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nintex.MyProfile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPermission
    {
        public int ID { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<int> PermissionId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
